# Generated by Django 5.0.1 on 2024-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('to_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=5000)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
