# Generated by Django 5.0.1 on 2024-06-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_fice_id_product_fingerprint_product_is_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
